files:
  - source: /HMCL/src/main/resources/assets/lang/I18N.properties
    translation: /HMCL/src/main/resources/assets/lang/I18N_%two_letters_code%.properties
    languages_mapping:
      two_letters_code:
        zh-CN: zh_CN
