name: Check Codes

on:
  push:
    paths:
      - '**.java'
      - '**.properties'
  pull_request:
    paths:
      - '**.java'
      - '**.properties'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test Run
        run: |
          echo "hello world"
