name: Check Codes

on:
  push:
    paths:
      - '**.java'
      - '**.properties'
  pull_request:
    paths:
      - '**.java'
      - '**.properties'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: 'jdk+fx'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-cleanup: never
      - name: Check Codes
        run: ./gradlew checkstyle checkTranslations --no-daemon --parallel --stacktrace || true
      - name: Set up reviewdog
        uses: reviewdog/action-setup@d8edfce3dd5e1ec6978745e801f9c50b5ef80252 # v1.4.0
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find . -path "*/build/reports/checkstyle/main.xml" | while read -r xml_file; do
            reviewdog -f=checkstyle \
                      -name="checkstyle" \
                      -reporter=github-pr-check \
                      -filter-mode=added \
                      "$xml_file"
          done
